# Removed all cameras

wamv_gps:
    - name: gps_wamv
      x: 0.0 # -0.85
wamv_imu:
    - name: imu_wamv
      y: 0.0 # -0.2
wamv_camera:
    - name: front_camera
      x: 0.75
      P: ${radians(15)}
lidar:
    - name: port_16
      type: 16_beam
      x: 0.8125
      y: 0.4925
      z: 1.255
      P: -8.55E-2
      Y: -2.3507
      
    - name: starboard_16
      type: 16_beam
      x: 0.8125
      y: -0.4925
      z: 1.255
      P: -8.55E-2
      Y: 2.3507
      
    - name: aft_16
      type: 16_beam
      x: -1.025
      z: 1.255
      P: -3.5E-2
      
